'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.42
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System


<System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
 Serializable(),  _
 System.ComponentModel.DesignerCategoryAttribute("code"),  _
 System.ComponentModel.ToolboxItem(true),  _
 System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema"),  _
 System.Xml.Serialization.XmlRootAttribute("Ds_Report"),  _
 System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")>  _
Partial Public Class Ds_Report
    Inherits System.Data.DataSet
    
    Private tableBC05 As BC05DataTable
    
    Private _schemaSerializationMode As System.Data.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Sub New()
        MyBase.New
        Me.BeginInit
        Me.InitClass
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler MyBase.Relations.CollectionChanged, schemaChangedHandler
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
        MyBase.New(info, context, false)
        If (Me.IsBinarySerialized(info, context) = true) Then
            Me.InitVars(false)
            Dim schemaChangedHandler1 As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
            AddHandler Me.Tables.CollectionChanged, schemaChangedHandler1
            AddHandler Me.Relations.CollectionChanged, schemaChangedHandler1
            Return
        End If
        Dim strSchema As String = CType(info.GetValue("XmlSchema", GetType(String)),String)
        If (Me.DetermineSchemaSerializationMode(info, context) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
            If (Not (ds.Tables("BC05")) Is Nothing) Then
                MyBase.Tables.Add(New BC05DataTable(ds.Tables("BC05")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXmlSchema(New System.Xml.XmlTextReader(New System.IO.StringReader(strSchema)))
        End If
        Me.GetSerializationData(info, context)
        Dim schemaChangedHandler As System.ComponentModel.CollectionChangeEventHandler = AddressOf Me.SchemaChanged
        AddHandler MyBase.Tables.CollectionChanged, schemaChangedHandler
        AddHandler Me.Relations.CollectionChanged, schemaChangedHandler
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.Browsable(false),  _
     System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)>  _
    Public ReadOnly Property BC05() As BC05DataTable
        Get
            Return Me.tableBC05
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.BrowsableAttribute(true),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)>  _
    Public Overrides Property SchemaSerializationMode() As System.Data.SchemaSerializationMode
        Get
            Return Me._schemaSerializationMode
        End Get
        Set
            Me._schemaSerializationMode = value
        End Set
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Tables() As System.Data.DataTableCollection
        Get
            Return MyBase.Tables
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)>  _
    Public Shadows ReadOnly Property Relations() As System.Data.DataRelationCollection
        Get
            Return MyBase.Relations
        End Get
    End Property
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub InitializeDerivedDataSet()
        Me.BeginInit
        Me.InitClass
        Me.EndInit
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Overrides Function Clone() As System.Data.DataSet
        Dim cln As Ds_Report = CType(MyBase.Clone,Ds_Report)
        cln.InitVars
        cln.SchemaSerializationMode = Me.SchemaSerializationMode
        Return cln
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeTables() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function ShouldSerializeRelations() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Sub ReadXmlSerializable(ByVal reader As System.Xml.XmlReader)
        If (Me.DetermineSchemaSerializationMode(reader) = System.Data.SchemaSerializationMode.IncludeSchema) Then
            Me.Reset
            Dim ds As System.Data.DataSet = New System.Data.DataSet
            ds.ReadXml(reader)
            If (Not (ds.Tables("BC05")) Is Nothing) Then
                MyBase.Tables.Add(New BC05DataTable(ds.Tables("BC05")))
            End If
            Me.DataSetName = ds.DataSetName
            Me.Prefix = ds.Prefix
            Me.Namespace = ds.Namespace
            Me.Locale = ds.Locale
            Me.CaseSensitive = ds.CaseSensitive
            Me.EnforceConstraints = ds.EnforceConstraints
            Me.Merge(ds, false, System.Data.MissingSchemaAction.Add)
            Me.InitVars
        Else
            Me.ReadXml(reader)
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Protected Overrides Function GetSchemaSerializable() As System.Xml.Schema.XmlSchema
        Dim stream As System.IO.MemoryStream = New System.IO.MemoryStream
        Me.WriteXmlSchema(New System.Xml.XmlTextWriter(stream, Nothing))
        stream.Position = 0
        Return System.Xml.Schema.XmlSchema.Read(New System.Xml.XmlTextReader(stream), Nothing)
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars()
        Me.InitVars(true)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Friend Overloads Sub InitVars(ByVal initTable As Boolean)
        Me.tableBC05 = CType(MyBase.Tables("BC05"),BC05DataTable)
        If (initTable = true) Then
            If (Not (Me.tableBC05) Is Nothing) Then
                Me.tableBC05.InitVars
            End If
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub InitClass()
        Me.DataSetName = "Ds_Report"
        Me.Prefix = ""
        Me.Namespace = "http://tempuri.org/Ds_Report.xsd"
        Me.EnforceConstraints = true
        Me.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema
        Me.tableBC05 = New BC05DataTable
        MyBase.Tables.Add(Me.tableBC05)
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Function ShouldSerializeBC05() As Boolean
        Return false
    End Function
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Private Sub SchemaChanged(ByVal sender As Object, ByVal e As System.ComponentModel.CollectionChangeEventArgs)
        If (e.Action = System.ComponentModel.CollectionChangeAction.Remove) Then
            Me.InitVars
        End If
    End Sub
    
    <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Shared Function GetTypedDataSetSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
        Dim ds As Ds_Report = New Ds_Report
        Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
        Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
        xs.Add(ds.GetSchemaSerializable)
        Dim any As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
        any.Namespace = ds.Namespace
        sequence.Items.Add(any)
        type.Particle = sequence
        Return type
    End Function
    
    Public Delegate Sub BC05RowChangeEventHandler(ByVal sender As Object, ByVal e As BC05RowChangeEvent)
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0"),  _
     System.Serializable(),  _
     System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")>  _
    Partial Public Class BC05DataTable
        Inherits System.Data.DataTable
        Implements System.Collections.IEnumerable
        
        Private columnc1 As System.Data.DataColumn
        
        Private columnc2 As System.Data.DataColumn
        
        Private columnc3 As System.Data.DataColumn
        
        Private columnc4 As System.Data.DataColumn
        
        Private columnc5 As System.Data.DataColumn
        
        Private columnc6 As System.Data.DataColumn
        
        Private columnc7 As System.Data.DataColumn
        
        Private columnc8 As System.Data.DataColumn
        
        Private columnc9 As System.Data.DataColumn
        
        Private columnc10 As System.Data.DataColumn
        
        Private columnc11 As System.Data.DataColumn
        
        Private columnc12 As System.Data.DataColumn
        
        Private columnc13 As System.Data.DataColumn
        
        Private columnc14 As System.Data.DataColumn
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New()
            MyBase.New
            Me.TableName = "BC05"
            Me.BeginInit
            Me.InitClass
            Me.EndInit
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal table As System.Data.DataTable)
            MyBase.New
            Me.TableName = table.TableName
            If (table.CaseSensitive <> table.DataSet.CaseSensitive) Then
                Me.CaseSensitive = table.CaseSensitive
            End If
            If (table.Locale.ToString <> table.DataSet.Locale.ToString) Then
                Me.Locale = table.Locale
            End If
            If (table.Namespace <> table.DataSet.Namespace) Then
                Me.Namespace = table.Namespace
            End If
            Me.Prefix = table.Prefix
            Me.MinimumCapacity = table.MinimumCapacity
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Sub New(ByVal info As System.Runtime.Serialization.SerializationInfo, ByVal context As System.Runtime.Serialization.StreamingContext)
            MyBase.New(info, context)
            Me.InitVars
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c1Column() As System.Data.DataColumn
            Get
                Return Me.columnc1
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c2Column() As System.Data.DataColumn
            Get
                Return Me.columnc2
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c3Column() As System.Data.DataColumn
            Get
                Return Me.columnc3
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c4Column() As System.Data.DataColumn
            Get
                Return Me.columnc4
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c5Column() As System.Data.DataColumn
            Get
                Return Me.columnc5
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c6Column() As System.Data.DataColumn
            Get
                Return Me.columnc6
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c7Column() As System.Data.DataColumn
            Get
                Return Me.columnc7
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c8Column() As System.Data.DataColumn
            Get
                Return Me.columnc8
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c9Column() As System.Data.DataColumn
            Get
                Return Me.columnc9
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c10Column() As System.Data.DataColumn
            Get
                Return Me.columnc10
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c11Column() As System.Data.DataColumn
            Get
                Return Me.columnc11
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c12Column() As System.Data.DataColumn
            Get
                Return Me.columnc12
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c13Column() As System.Data.DataColumn
            Get
                Return Me.columnc13
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property c14Column() As System.Data.DataColumn
            Get
                Return Me.columnc14
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         System.ComponentModel.Browsable(false)>  _
        Public ReadOnly Property Count() As Integer
            Get
                Return Me.Rows.Count
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Default ReadOnly Property Item(ByVal index As Integer) As BC05Row
            Get
                Return CType(Me.Rows(index),BC05Row)
            End Get
        End Property
        
        Public Event BC05RowChanging As BC05RowChangeEventHandler
        
        Public Event BC05RowChanged As BC05RowChangeEventHandler
        
        Public Event BC05RowDeleting As BC05RowChangeEventHandler
        
        Public Event BC05RowDeleted As BC05RowChangeEventHandler
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Sub AddBC05Row(ByVal row As BC05Row)
            Me.Rows.Add(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overloads Function AddBC05Row(ByVal c1 As String, ByVal c2 As String, ByVal c3 As String, ByVal c4 As String, ByVal c5 As String, ByVal c6 As String, ByVal c7 As String, ByVal c8 As String, ByVal c9 As String, ByVal c10 As String, ByVal c11 As String, ByVal c12 As String, ByVal c13 As String, ByVal c14 As String) As BC05Row
            Dim rowBC05Row As BC05Row = CType(Me.NewRow,BC05Row)
            rowBC05Row.ItemArray = New Object() {c1, c2, c3, c4, c5, c6, c7, c8, c9, c10, c11, c12, c13, c14}
            Me.Rows.Add(rowBC05Row)
            Return rowBC05Row
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overridable Function GetEnumerator() As System.Collections.IEnumerator Implements System.Collections.IEnumerable.GetEnumerator
            Return Me.Rows.GetEnumerator
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Overrides Function Clone() As System.Data.DataTable
            Dim cln As BC05DataTable = CType(MyBase.Clone,BC05DataTable)
            cln.InitVars
            Return cln
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function CreateInstance() As System.Data.DataTable
            Return New BC05DataTable
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub InitVars()
            Me.columnc1 = MyBase.Columns("c1")
            Me.columnc2 = MyBase.Columns("c2")
            Me.columnc3 = MyBase.Columns("c3")
            Me.columnc4 = MyBase.Columns("c4")
            Me.columnc5 = MyBase.Columns("c5")
            Me.columnc6 = MyBase.Columns("c6")
            Me.columnc7 = MyBase.Columns("c7")
            Me.columnc8 = MyBase.Columns("c8")
            Me.columnc9 = MyBase.Columns("c9")
            Me.columnc10 = MyBase.Columns("c10")
            Me.columnc11 = MyBase.Columns("c11")
            Me.columnc12 = MyBase.Columns("c12")
            Me.columnc13 = MyBase.Columns("c13")
            Me.columnc14 = MyBase.Columns("c14")
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Private Sub InitClass()
            Me.columnc1 = New System.Data.DataColumn("c1", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc1)
            Me.columnc2 = New System.Data.DataColumn("c2", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc2)
            Me.columnc3 = New System.Data.DataColumn("c3", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc3)
            Me.columnc4 = New System.Data.DataColumn("c4", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc4)
            Me.columnc5 = New System.Data.DataColumn("c5", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc5)
            Me.columnc6 = New System.Data.DataColumn("c6", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc6)
            Me.columnc7 = New System.Data.DataColumn("c7", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc7)
            Me.columnc8 = New System.Data.DataColumn("c8", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc8)
            Me.columnc9 = New System.Data.DataColumn("c9", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc9)
            Me.columnc10 = New System.Data.DataColumn("c10", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc10)
            Me.columnc11 = New System.Data.DataColumn("c11", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc11)
            Me.columnc12 = New System.Data.DataColumn("c12", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc12)
            Me.columnc13 = New System.Data.DataColumn("c13", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc13)
            Me.columnc14 = New System.Data.DataColumn("c14", GetType(String), Nothing, System.Data.MappingType.Element)
            MyBase.Columns.Add(Me.columnc14)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function NewBC05Row() As BC05Row
            Return CType(Me.NewRow,BC05Row)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function NewRowFromBuilder(ByVal builder As System.Data.DataRowBuilder) As System.Data.DataRow
            Return New BC05Row(builder)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Function GetRowType() As System.Type
            Return GetType(BC05Row)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanged(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanged(e)
            If (Not (Me.BC05RowChangedEvent) Is Nothing) Then
                RaiseEvent BC05RowChanged(Me, New BC05RowChangeEvent(CType(e.Row,BC05Row), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowChanging(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowChanging(e)
            If (Not (Me.BC05RowChangingEvent) Is Nothing) Then
                RaiseEvent BC05RowChanging(Me, New BC05RowChangeEvent(CType(e.Row,BC05Row), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleted(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleted(e)
            If (Not (Me.BC05RowDeletedEvent) Is Nothing) Then
                RaiseEvent BC05RowDeleted(Me, New BC05RowChangeEvent(CType(e.Row,BC05Row), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Protected Overrides Sub OnRowDeleting(ByVal e As System.Data.DataRowChangeEventArgs)
            MyBase.OnRowDeleting(e)
            If (Not (Me.BC05RowDeletingEvent) Is Nothing) Then
                RaiseEvent BC05RowDeleting(Me, New BC05RowChangeEvent(CType(e.Row,BC05Row), e.Action))
            End If
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub RemoveBC05Row(ByVal row As BC05Row)
            Me.Rows.Remove(row)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Shared Function GetTypedTableSchema(ByVal xs As System.Xml.Schema.XmlSchemaSet) As System.Xml.Schema.XmlSchemaComplexType
            Dim type As System.Xml.Schema.XmlSchemaComplexType = New System.Xml.Schema.XmlSchemaComplexType
            Dim sequence As System.Xml.Schema.XmlSchemaSequence = New System.Xml.Schema.XmlSchemaSequence
            Dim ds As Ds_Report = New Ds_Report
            xs.Add(ds.GetSchemaSerializable)
            Dim any1 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any1.Namespace = "http://www.w3.org/2001/XMLSchema"
            any1.MinOccurs = New Decimal(0)
            any1.MaxOccurs = Decimal.MaxValue
            any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any1)
            Dim any2 As System.Xml.Schema.XmlSchemaAny = New System.Xml.Schema.XmlSchemaAny
            any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1"
            any2.MinOccurs = New Decimal(1)
            any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax
            sequence.Items.Add(any2)
            Dim attribute1 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute1.Name = "namespace"
            attribute1.FixedValue = ds.Namespace
            type.Attributes.Add(attribute1)
            Dim attribute2 As System.Xml.Schema.XmlSchemaAttribute = New System.Xml.Schema.XmlSchemaAttribute
            attribute2.Name = "tableTypeName"
            attribute2.FixedValue = "BC05DataTable"
            type.Attributes.Add(attribute2)
            type.Particle = sequence
            Return type
        End Function
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Partial Public Class BC05Row
        Inherits System.Data.DataRow
        
        Private tableBC05 As BC05DataTable
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Friend Sub New(ByVal rb As System.Data.DataRowBuilder)
            MyBase.New(rb)
            Me.tableBC05 = CType(Me.Table,BC05DataTable)
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c1() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c1Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c1' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c1Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c2() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c2Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c2' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c2Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c3() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c3Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c3' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c3Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c4() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c4Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c4' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c4Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c5() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c5Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c5' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c5Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c6() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c6Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c6' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c6Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c7() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c7Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c7' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c7Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c8() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c8Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c8' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c8Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c9() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c9Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c9' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c9Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c10() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c10Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c10' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c10Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c11() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c11Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c11' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c11Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c12() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c12Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c12' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c12Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c13() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c13Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c13' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c13Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Property c14() As String
            Get
                Try 
                    Return CType(Me(Me.tableBC05.c14Column),String)
                Catch e As System.InvalidCastException
                    Throw New System.Data.StrongTypingException("The value for column 'c14' in table 'BC05' is DBNull.", e)
                End Try
            End Get
            Set
                Me(Me.tableBC05.c14Column) = value
            End Set
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc1Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c1Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc1Null()
            Me(Me.tableBC05.c1Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc2Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c2Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc2Null()
            Me(Me.tableBC05.c2Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc3Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c3Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc3Null()
            Me(Me.tableBC05.c3Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc4Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c4Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc4Null()
            Me(Me.tableBC05.c4Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc5Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c5Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc5Null()
            Me(Me.tableBC05.c5Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc6Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c6Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc6Null()
            Me(Me.tableBC05.c6Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc7Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c7Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc7Null()
            Me(Me.tableBC05.c7Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc8Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c8Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc8Null()
            Me(Me.tableBC05.c8Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc9Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c9Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc9Null()
            Me(Me.tableBC05.c9Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc10Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c10Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc10Null()
            Me(Me.tableBC05.c10Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc11Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c11Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc11Null()
            Me(Me.tableBC05.c11Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc12Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c12Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc12Null()
            Me(Me.tableBC05.c12Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc13Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c13Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc13Null()
            Me(Me.tableBC05.c13Column) = System.Convert.DBNull
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Function Isc14Null() As Boolean
            Return Me.IsNull(Me.tableBC05.c14Column)
        End Function
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub Setc14Null()
            Me(Me.tableBC05.c14Column) = System.Convert.DBNull
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")>  _
    Public Class BC05RowChangeEvent
        Inherits System.EventArgs
        
        Private eventRow As BC05Row
        
        Private eventAction As System.Data.DataRowAction
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public Sub New(ByVal row As BC05Row, ByVal action As System.Data.DataRowAction)
            MyBase.New
            Me.eventRow = row
            Me.eventAction = action
        End Sub
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Row() As BC05Row
            Get
                Return Me.eventRow
            End Get
        End Property
        
        <System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
        Public ReadOnly Property Action() As System.Data.DataRowAction
            Get
                Return Me.eventAction
            End Get
        End Property
    End Class
End Class
